export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_GOOGLE_LOGIN_REQUEST = 'USER_GOOGLE_LOGIN_REQUEST'
export const USER_GOOGLE_LOGIN_SUCCESS = 'USER_GOOGLE_LOGIN_SUCCESS'
export const USER_GOOGLE_LOGIN_FAIL = 'USER_GOOGLE_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'


export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_BLOCK_REQUEST = 'USER_BLOCK_REQUEST'
export const USER_BLOCK_SUCCESS = 'USER_BLOCK_SUCCESS'
export const USER_BLOCK_FAIL = 'USER_BLOCK_FAIL'

export const USER_FETCHPIC_REQUEST = 'USER_FETCHPIC_REQUEST'
export const USER_FETCHPIC_SUCCESS = 'USER_FETCHPIC_SUCCESS'
export const USER_FETCHPIC_FAIL = 'USER_FETCHPIC_FAIL'

export const USER_UPDATE_PROFILE_PIC = 'USER_UPDATE_PROFILE_PIC'


export const USER_OTP_LOGIN_REQUEST = 'USER_OTP_LOGIN_REQUEST'
export const USER_OTP_LOGIN_SUCCESS = 'USER_OTP_LOGIN_SUCCESS'
export const USER_OTP_LOGIN_FAIL = 'USER_OTP_LOGIN_FAIL'

